name: Docker CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:

  build:
    runs-on: ubuntu-20.04 
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: create .env file
      run: |
        touch .env
        echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env
        echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
        echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> .env
        cat .env
      env: 
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }} 
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }} 

    - name: Build the Docker image
      run: |
        cd frontend
        docker build . --file Dockerfile --tag frontend:$(date +%s)
