name: Docker CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:

  build:
    runs-on:  ubuntu-20.04
    steps: 
    -
      name: Checkout code
      uses: actions/checkout@v2
    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push to Docker Hub
      uses: docker/build-push-action@v3
      with: 
          context: .
          push: true
          tags: martijnbassa/kwetter-frontend:latest

